# Generated by Django 6.1 on 2026-08-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã nhóm (VD: A, B, C, D)')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả nhóm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Nhóm khảo sát',
                'verbose_name_plural': 'Các nhóm khảo sát',
                'ordering': ['order'],
            },
        ),
    ]
