# Generated by Django 6.1 on 2026-08-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='school_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lớp / Đơn vị'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ và tên'),
        ),
    ]
