"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-me=9scm@(3^bzitbyw_-7x!v7w(zniu_vy4ooa0l9nl4ebynt6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
   
   
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', # Bắt buộc cho allauth
    # 1. Khai báo các app của Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    # 2. Khai báo nhà cung cấp Social Auth (Ví dụ Google, Facebook)
    'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.facebook',
    'users', # Khai báo app users
    'core',     # Các module cốt lõi của hệ thống, ví dụ: User, Profile, Permission, Role
    'questions', # Quản lý Ngân hàng câu hỏi, Đáp án, Danh mục
    'surveys',   # Quản lý Bộ khảo sát, Lượt nộp, Chấm điểm
    'pages.apps.PagesConfig',
    'polls.apps.PollsConfig',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Thêm dòng Middleware của Allauth bên dưới
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'hikikocheck',  # Tên cơ sở dữ liệu PostgreSQL của bạn
        'USER': 'postgres',
        'PASSWORD': 'root',
        'HOST': 'localhost',  # Hoặc địa chỉ IP của server PostgreSQL
        'PORT': '5432',       # Cổng mặc định của PostgreSQL
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Đường dẫn URL để truy cập các tệp media từ trình duyệt (ví dụ: http://127.0.0.1:8000/media/avatars/abc.jpg)
MEDIA_URL = '/media/'

# Thư mục thực tế trên ổ đĩa lưu trữ các tệp tải lên
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTHENTICATION_BACKENDS = [
    # Mặc định của Django
    'django.contrib.auth.backends.ModelBackend',
    
    # Sửa 'auth_backend' thành 'auth_backends' (có chữ 's')
    'allauth.account.auth_backends.AuthenticationBackend',
]
# Cấu hình URL điều hướng
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'pages:home'
LOGOUT_REDIRECT_URL = 'users:login'

# Cấu hình bổ sung riêng cho django-allauth
SITE_ID = 1

# Phương thức đăng nhập (cho phép dùng tên đăng nhập hoặc email)
ACCOUNT_LOGIN_METHODS = {'username', 'email'}

# Các trường bắt buộc khi đăng ký tài khoản
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
DEFAULT_FROM_EMAIL = 'HikikoCheck System <noreply@hikikocheck.com>'