# Generated by Django 6.1 on 2026-08-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='email',
            field=models.EmailField(blank=True, help_text='Email của người làm khảo sát', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
