# Generated by Django 6.1 on 2026-08-15 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group'),
        ('surveys', '0003_submission_email_submission_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_difficulties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveyresultthreshold',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.group', verbose_name='Áp dụng cho nhóm (Bỏ trống nếu là tổng hợp chung)'),
        ),
    ]
