# Generated by Django 6.1 on 2026-08-15 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group'),
        ('surveys', '0004_submission_score_a_submission_score_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresultthreshold',
            name='description',
            field=models.TextField(verbose_name='Nhận xét chi tiết'),
        ),
        migrations.AlterField(
            model_name='surveyresultthreshold',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.group', verbose_name='Áp dụng cho nhóm (Chọn nhóm A, B, C, D hoặc nhóm tổng hợp ALL_ABC, ALL_D)'),
        ),
        migrations.AlterField(
            model_name='surveyresultthreshold',
            name='recommendation',
            field=models.TextField(blank=True, null=True, verbose_name='Lời khuyên'),
        ),
        migrations.AlterField(
            model_name='surveyresultthreshold',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Mức độ'),
        ),
    ]
