# Generated by Django 6.1 on 2026-08-18 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_surveyresultthreshold_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên bộ khảo sát')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả bộ khảo sát')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bộ khảo sát tổng hợp',
                'verbose_name_plural': 'Các bộ khảo sát tổng hợp',
            },
        ),
        migrations.AlterField(
            model_name='submission',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='submission',
            name='composite_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='surveys.compositesurvey', verbose_name='Thuộc bộ khảo sát'),
        ),
        migrations.CreateModel(
            name='CompositeSurveyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự hiển thị (Phần thứ N)')),
                ('composite_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='surveys.compositesurvey')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey', verbose_name='Phần khảo sát')),
            ],
            options={
                'verbose_name': 'Cấu trúc phần khảo sát',
                'verbose_name_plural': 'Cấu trúc các phần khảo sát',
                'ordering': ['order'],
                'unique_together': {('composite_survey', 'order')},
            },
        ),
        migrations.AddField(
            model_name='compositesurvey',
            name='surveys',
            field=models.ManyToManyField(related_name='composite_surveys', through='surveys.CompositeSurveyItem', to='surveys.survey', verbose_name='Các phần khảo sát thành phần'),
        ),
    ]
