# Generated by Django 6.1 on 2026-08-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_compositesurvey_alter_submission_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositesurveyitem',
            name='name',
            field=models.CharField(blank=True, help_text='VD: Phần I, Phần II, Chương 1... (Nếu để trống sẽ dùng tên mặc định của bài khảo sát)', max_length=255, null=True, verbose_name='Tên phần hiển thị'),
        ),
    ]
