# Generated by Django 6.1 on 2026-08-18 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lead_school_class_alter_lead_email_and_more'),
        ('surveys', '0007_compositesurveyitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='core.lead', verbose_name='Người tham gia (Lead)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.EmailField(blank=True, help_text='Email của người làm khảo sát (tùy chọn)', max_length=254, null=True),
        ),
    ]
