# Generated by Django 6.1 on 2026-08-19 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_submission_lead_alter_submission_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Điểm đạt được')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_results', to='surveys.submission', verbose_name='Lượt làm bài')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey', verbose_name='Khảo sát con')),
            ],
            options={
                'verbose_name': 'Kết quả khảo sát con',
                'verbose_name_plural': 'Kết quả các khảo sát con',
                'unique_together': {('submission', 'survey')},
            },
        ),
    ]
